### ISSUE TITLE
[discuss] release version 1.0

### ISSUE THREAD

**Issue by membphis** [peposso/lua-tinyyaml#6]
how about we release one version 1.0 ?

I think we can do this after the PR https://github.com/peposso/lua-tinyyaml/pull/5 is merged.

**Comment by peposso** [comment]
sounds good to me.

**Comment by membphis** [comment]
@peposso you can create a tag now, the name can be `1.0` .

Then I will submit a new luarocks file by PR.

**Comment by peposso** [comment]
@membphis I pushed `1.0` tag.

**Comment by peposso** [comment]
done.
